default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
      
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --exclude=.+/migrations/
          - --max-line-length=88
          - --ignore=E501,W503,E203
  
